# Chat API Contract
# Feature: 001-fix-chat-field-mismatch
# Date: 2025-12-27

openapi: "3.0.3"
info:
  title: Chat API
  description: API contract for the chat endpoint
  version: "1.0.0"

paths:
  /api/v1/chat:
    post:
      summary: Send chat message
      description: Send a message to the RAG-powered chat assistant
      operationId: sendChatMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatMessageRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatMessageResponse'
        '400':
          description: Bad Request - Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                emptyMessage:
                  summary: Empty message error
                  value:
                    detail: "Message is required"
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                serverError:
                  summary: Server error
                  value:
                    detail: "Internal server error"

components:
  schemas:
    ChatMessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's question or input text
          minLength: 1
          example: "What is ROS 2?"
        session_id:
          type: string
          description: Session identifier for conversation continuity
          example: "550e8400-e29b-41d4-a716-446655440000"
        selected_text:
          type: string
          description: Optional selected text from page for context
        user_preferences:
          type: object
          description: User personalization preferences
        retrieval_mode:
          type: string
          description: RAG retrieval mode
          default: "full-book"
          enum:
            - full-book
            - page-context
        metadata_filters:
          type: object
          description: Optional filters for RAG retrieval

    ChatMessageResponse:
      type: object
      required:
        - response
        - session_id
        - citations
        - response_time_ms
        - timestamp
      properties:
        response:
          type: string
          description: AI-generated response text
          example: "ROS 2 (Robot Operating System 2) is..."
        session_id:
          type: string
          description: Session ID for conversation
        citations:
          type: array
          items:
            type: string
          description: List of chunk IDs used for context
        response_time_ms:
          type: number
          description: Processing time in milliseconds
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error description
