openapi: 3.0.0
info:
  title: RAG Chat API
  version: 1.0.0
  description: API for RAG-based chat functionality with textbook content
servers:
  - url: http://localhost:8000
    description: Development server

paths:
  /api/v1/chat:
    post:
      summary: Chat with RAG system
      description: Send a message to the chat system with optional selected text and user preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - message
              properties:
                message:
                  type: string
                  description: The user's message
                  example: "Explain how ROS 2 works"
                selected_text:
                  type: string
                  description: Optional selected text from the frontend to use as context
                  example: "ROS 2 (Robot Operating System 2) is a flexible framework for writing robot applications..."
                user_preferences:
                  type: object
                  properties:
                    language:
                      type: string
                      description: Preferred language for response
                      example: "en"
                    learning_level:
                      type: string
                      description: User's learning level for personalization
                      enum: [beginner, intermediate, advanced]
                      example: "beginner"
      responses:
        '200':
          description: Successful response from the chat system
          content:
            application/json:
              schema:
                type: object
                properties:
                  response:
                    type: string
                    description: The AI-generated response
                    example: "ROS 2 is a flexible framework for writing robot applications..."
                  citations:
                    type: array
                    items:
                      type: object
                      properties:
                        source:
                          type: string
                          description: Source of the cited information
                          example: "Chapter 3.2: ROS 2 Architecture"
                        page:
                          type: string
                          description: Page or section reference
                          example: "Module 1, Section 3.2"
                  context_used:
                    type: string
                    description: Context that was used from selected text
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Message is required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Internal server error occurred"

  /api/v1/translate:
    post:
      summary: Translate text
      description: Translate text content to the specified language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - text
                - target_language
              properties:
                text:
                  type: string
                  description: Text to translate
                  example: "Robot Operating System is a middleware for robotics applications"
                target_language:
                  type: string
                  description: Target language code (e.g., en, ur, es)
                  example: "ur"
                source_language:
                  type: string
                  description: Source language code (optional, auto-detected if not provided)
                  example: "en"
      responses:
        '200':
          description: Successfully translated text
          content:
            application/json:
              schema:
                type: object
                properties:
                  translated_text:
                    type: string
                    description: The translated text
                    example: "روبوٹ آپریٹنگ سسٹم روبوٹکس ایپلی کیشنز کے لیے ایک مڈل ویئر ہے"
                  source_language:
                    type: string
                    description: Detected or provided source language
                    example: "en"
                  target_language:
                    type: string
                    description: Target language
                    example: "ur"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Text and target_language are required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Translation service unavailable"

  /api/v1/personalize:
    post:
      summary: Personalize content
      description: Adjust content complexity based on user preferences
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - learning_level
              properties:
                content:
                  type: string
                  description: Content to personalize
                  example: "Advanced machine learning concepts in robotics..."
                learning_level:
                  type: string
                  enum: [beginner, intermediate, advanced]
                  description: Target learning level
                  example: "beginner"
                user_preferences:
                  type: object
                  properties:
                    language:
                      type: string
                      description: Preferred language
                      example: "en"
                    additional_context:
                      type: string
                      description: Additional context for personalization
                      example: "User is studying robotics for the first time"
      responses:
        '200':
          description: Personalized content
          content:
            application/json:
              schema:
                type: object
                properties:
                  personalized_content:
                    type: string
                    description: The personalized content
                    example: "Machine learning in robotics is like teaching robots to learn from experience..."
                  original_complexity:
                    type: string
                    description: Original complexity level
                    example: "advanced"
                  new_complexity:
                    type: string
                    description: New complexity level after personalization
                    example: "beginner"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Content and learning_level are required"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Personalization service unavailable"

  /api/v1/health:
    get:
      summary: Health check
      description: Check the health status of the API
      responses:
        '200':
          description: API is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "healthy"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2025-12-17T10:00:00Z"
                  version:
                    type: string
                    example: "1.0.0"